import type { Lesson } from "@/lib/lessons";

/**
 * Lazy lesson registry — one dynamic import per lesson so a lesson's demo
 * components are only bundled for its own route. Keep keys in sync with
 * LESSON_META in lib/lessons.ts (the lesson page validates both at build).
 */
export const LESSON_LOADERS: Record<string, () => Promise<{ default: Lesson }>> = {
  tokenization: () => import("./tokenization"),
  embeddings: () => import("./embeddings"),
  "temperature-sampling": () => import("./temperature-sampling"),
  attention: () => import("./attention"),
  "context-windows": () => import("./context-windows"),
  hallucination: () => import("./hallucination"),
  rag: () => import("./rag"),
  "prompt-engineering": () => import("./prompt-engineering"),
  agents: () => import("./agents"),
  training: () => import("./training"),
  "neural-networks": () => import("./neural-networks"),
  "gradient-descent": () => import("./gradient-descent"),
  "overfitting-underfitting": () => import("./overfitting-underfitting"),
  "chain-of-thought": () => import("./chain-of-thought"),
  "reasoning-models": () => import("./reasoning-models"),
  diffusion: () => import("./diffusion"),
  "function-calling": () => import("./function-calling"),
  evals: () => import("./evals"),
  "fine-tuning": () => import("./fine-tuning"),
  rlhf: () => import("./rlhf"),
  dpo: () => import("./dpo"),
  "prompt-injection": () => import("./prompt-injection"),
  "in-context-learning": () => import("./in-context-learning"),
  "mixture-of-experts": () => import("./mixture-of-experts"),
  quantization: () => import("./quantization"),
  distillation: () => import("./distillation"),
  alignment: () => import("./alignment"),
  jailbreaks: () => import("./jailbreaks"),
  "constitutional-ai": () => import("./constitutional-ai"),
  multimodal: () => import("./multimodal"),
  "vision-language-models": () => import("./vision-language-models"),
  "scaling-laws": () => import("./scaling-laws"),
  "agentic-memory": () => import("./agentic-memory"),
  multiagent: () => import("./multiagent"),
  "retrieval-rerank": () => import("./retrieval-rerank"),
  "structured-output": () => import("./structured-output"),
  "synthetic-data": () => import("./synthetic-data"),
  "model-collapse": () => import("./model-collapse"),
  "kv-cache": () => import("./kv-cache"),
  mcp: () => import("./mcp"),
  "model-cards": () => import("./model-cards"),
  watermarking: () => import("./watermarking"),
  "what-is-ai": () => import("./what-is-ai"),
  "data-and-datasets": () => import("./data-and-datasets"),
  "statistics-essentials": () => import("./statistics-essentials"),
  "probability-and-uncertainty": () => import("./probability-and-uncertainty"),
};
