import type { Lesson } from "@/lib/lessons";
import SyntheticDataDemo from "@/components/learn/SyntheticDataDemo";

const lesson: Lesson = {
  slug: "synthetic-data",
  title: "Synthetic Data",
  tagline: "When the training data is generated, not collected.",
  minutes: 6,
  steps: [
    {
      kind: "explain",
      id: "hook",
      eyebrow: "The idea",
      body: (
        <>
          <p style={{ margin: 0 }}>
            Real data is expensive, messy, privacy-laden, and sometimes just
            doesn&apos;t exist for the case you need. So teams increasingly{" "}
            <em>make</em> it: have a model or a simulation generate examples to
            train on.
          </p>
          <p style={{ margin: "1em 0 0" }}>
            That&apos;s <strong>synthetic data</strong> — and it&apos;s a double-
            edged tool.
          </p>
        </>
      ),
    },
    {
      kind: "explain",
      id: "why",
      eyebrow: "Why generate it",
      body: (
        <>
          <p style={{ margin: 0 }}>
            Synthetic data fills gaps real data won&apos;t: rare edge cases you
            can&apos;t collect enough of, sensitive records you can&apos;t use
            directly, or perfectly labelled examples that would cost a fortune to
            annotate by hand. You can produce exactly the distribution you want.
          </p>
          <p style={{ margin: "1em 0 0" }}>
            Used well — to <em>augment</em> real data, or in domains where it can
            be checked — it&apos;s genuinely powerful.
          </p>
        </>
      ),
    },
    {
      kind: "check",
      id: "check-what",
      prompt: "What is synthetic data?",
      choices: [
        {
          text: "Data generated by a model or simulation rather than collected from the real world",
          correct: true,
          feedback:
            "Right — manufactured examples, not gathered ones.",
        },
        {
          text: "Data stored in a fake or temporary database",
          feedback:
            "It's about how the data was *produced*, not where it's stored.",
        },
        {
          text: "Data that has been deleted to save space",
          feedback:
            "Synthetic means generated, not removed.",
        },
      ],
    },
    {
      kind: "interact",
      id: "demo",
      body: (
        <p style={{ margin: 0 }}>
          Generate a batch of synthetic examples and compare them to the real
          distribution. Notice what the generator captures — and what it quietly
          smooths away.
        </p>
      ),
      demo: SyntheticDataDemo,
      tryThis: "The rare, weird cases at the edges are the first thing a generator tends to miss.",
    },
    {
      kind: "check",
      id: "check-risk",
      prompt: "What's the core risk of training on a model's synthetic data?",
      choices: [
        {
          text: "It inherits and can amplify the generating model's biases and blind spots",
          correct: true,
          feedback:
            "Right — synthetic data is a mirror of its maker, so its flaws get baked in and magnified.",
        },
        {
          text: "It's always perfectly representative of reality",
          feedback:
            "The opposite worry — it reflects the generator, not the messy real world, and can miss the edges.",
        },
        {
          text: "It can't be labelled",
          feedback:
            "Clean labels are actually a selling point — the risk is representativeness and inherited bias.",
        },
      ],
    },
    {
      kind: "explain",
      id: "feedback-loop",
      eyebrow: "The loop to fear",
      body: (
        <>
          <p style={{ margin: 0 }}>
            The real danger is recursion. Train a model heavily on another
            model&apos;s output, whose output trains the next model, and small
            distortions compound. The rare cases thin out, variety drains away,
            and quality quietly erodes generation after generation.
          </p>
          <p style={{ margin: "1em 0 0" }}>
            Synthetic data is a fine ingredient. As the <em>whole diet</em>, it
            curdles.
          </p>
        </>
      ),
    },
    {
      kind: "check",
      id: "check-best",
      prompt: "What's the healthier way to use synthetic data?",
      choices: [
        {
          text: "As a supplement to real data — augmenting and filling gaps, not replacing the real distribution",
          correct: true,
          feedback:
            "Right — anchored to real data and checked where possible, it helps; as the entire diet, it degrades models.",
        },
        {
          text: "As a complete, permanent replacement for all real data",
          feedback:
            "That's exactly the recipe for compounding distortion across generations.",
        },
        {
          text: "Only if you never check it against reality",
          feedback:
            "Backwards — verifying against real data is what keeps synthetic data honest.",
        },
      ],
    },
    {
      kind: "explain",
      id: "wrap",
      eyebrow: "Keep this",
      body: (
        <>
          <p style={{ margin: 0 }}>
            Synthetic data lets you manufacture exactly the examples you need —
            powerful for gaps, edge cases, and privacy. But it mirrors its
            generator, so lean on it to <em>augment</em> real data, not to
            replace it.
          </p>
          <p style={{ margin: "1em 0 0" }}>
            Lean too hard and you risk <strong>model collapse</strong> — the next
            lesson.
          </p>
        </>
      ),
    },
  ],
};

export default lesson;
