import { notFound } from "next/navigation";
import type { Metadata } from "next";
import type { Node, Edge } from "@xyflow/react";
import { createServiceClient } from "@/utils/supabase/service";
import RoadmapCanvas from "@/components/RoadmapCanvas";
import type { ToolNodeData } from "@/components/ToolNode";

type Props = { params: Promise<{ id: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params;
  const supabase = createServiceClient();
  const { data } = await supabase
    .from("roadmaps")
    .select("title, is_public, nodes_json")
    .eq("id", id)
    .single();

  if (!data?.is_public) return { title: "AIght" };

  const nodeCount = Array.isArray(data.nodes_json) ? data.nodes_json.length : 0;
  const title       = `${data.title} — shared on AIght`;
  const description = `Explore this curated AI tool pipeline on AIght. ${nodeCount} tool${nodeCount === 1 ? "" : "s"}, step by step. Clone it to your own account in one click.`;
  const url         = `${process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.aightai.in"}/r/${id}`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      url,
      siteName: "AIght",
      type:     "website",
      // Dynamic OG image is generated by app/r/[id]/opengraph-image.tsx
    },
    twitter: {
      card:        "summary_large_image",
      title,
      description,
      // Dynamic OG image is auto-injected from opengraph-image.tsx
    },
  };
}

export default async function PublicRoadmapPage({ params }: Props) {
  const { id } = await params;

  const supabase = createServiceClient();
  const { data: roadmap } = await supabase
    .from("roadmaps")
    .select("id, title, nodes_json, edges_json, is_public")
    .eq("id", id)
    .single();

  if (!roadmap || !roadmap.is_public) notFound();

  const nodes = Array.isArray(roadmap.nodes_json)
    ? (roadmap.nodes_json as Node<ToolNodeData>[])
    : [];

  const edges = Array.isArray(roadmap.edges_json)
    ? (roadmap.edges_json as Edge[])
    : [];

  return (
    <RoadmapCanvas
      roadmapId={roadmap.id}
      title={roadmap.title}
      initialNodes={nodes}
      initialEdges={edges}
      readOnly
    />
  );
}
